### ISSUE TITLE
node server not starting error:  Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by khalidMhd** [akkii922/google-meet-clone#1]
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}

**Comment by akkii922** [comment]
Please check if your Redis server is running correctly.

**Comment by CoderZ90** [comment]
> Please check if your Redis server is running correctly.

It same coming for me how do i fix it ? everything is installed

Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
errno: -4078,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 6379
}

**Comment by abhi27-web** [comment]
Even i am facing the same issue

**Comment by Jamesbansal** [comment]
> 
> 
> Please check if your Redis server is running correctly.

How to check that?

**Comment by alooperalta** [comment]
I am facing the same issue, it's pretty urgent, please help!!

**Comment by parthranawat** [comment]
install redis
new terminal - redis-server
